#!/bin/bash

# Exit on command errors and treat unset variables as an error
set -eu

# This is a multi-instance app, meaning it can be installed several times independently
# The id of the app as stated in the manifest is available as $YNH_APP_ID
# The instance number is available as $YNH_APP_INSTANCE_NUMBER (equals "1", "2", ...)
# The app instance name is available as $YNH_APP_INSTANCE_NAME
#    - the first time the app is installed, YNH_APP_INSTANCE_NAME = ynhexample
#    - the second time the app is installed, YNH_APP_INSTANCE_NAME = ynhexample__2
#    - ynhexample__{N} for the subsequent installations, with N=3,4, ...
# The app instance name is probably what you are interested the most, since this is
# guaranteed to be unique. This is a good unique identifier to define installation path,
# db names, ...
app=$YNH_APP_INSTANCE_NAME

# Retrieve arguments
domain=$YNH_APP_ARG_DOMAIN
path_url=$YNH_APP_ARG_PATH
user=$YNH_APP_ARG_ADMIN

# Retrieve arguments
user_pwd=$4
user_pwd=$(echo -n $user_pwd | md5sum | cut -d ' ' -f 1)

# Check that user has an existing account
sudo yunohost user list --json | grep -q "\"username\": \"$user\""
if [[ ! $? -eq 0 ]]; then
echo "Error : the chosen user does not exist"
    exit 1
fi

# Store settings for further usage
sudo yunohost app setting lychee user -v $user
sudo yunohost app setting lychee user_pwd -v $user_pwd

# Check domain/path availability
sudo yunohost app checkurl $domain$path -a lychee
if [[ ! $? -eq 0 ]]; then
    exit 1
fi
#db
db_pwd=$(dd if=/dev/urandom bs=1 count=200 2> /dev/null | tr -c -d '[A-Za-z0-9]' | sed -n 's/\(.\{24\}\).*/\1/p')
db_user=lychee

# Initialize database and store mysql password for upgrade
sudo yunohost app initdb $db_user -p $db_pwd -s $(readlink -e ../conf/db.sql) 
sudo yunohost app setting lychee mysqlpwd -v $db_pwd

# Remove trailing "/" for next commands
path=${path%/}

# Copy files to the right place
final_path=/var/www/lychee
data_path=/home/yunohost.app/lychee/

sudo mkdir -p $final_path
sudo mkdir -p $data_path
sudo cp -r ../source/* $final_path
sudo cp ../conf/php-fpm.conf /etc/php5/fpm/pool.d/lychee.conf
sudo cp ../conf/php-fpm.ini /etc/php5/fpm/conf.d/20-lychee.ini
sudo cp ../conf/config.php $final_path/data/
sudo mv $final_path/uploads/* $data_path
sudo rmdir $final_path/uploads/
sudo ln -s $data_path $final_path/uploads

# Set permissions to lychee directory
sudo chown -R www-data: $final_path
sudo chown -R www-data: $data_path

# Modify Nginx configuration file and copy it to Nginx conf directory
if [ -z "$path" ]; then
    path="/"
fi
sudo sed -i "s@NAMETOCHANGE@lychee@g" /etc/php5/fpm/pool.d/lychee.conf
sudo sed -i "s@NAMETOCHANGE@lychee@g" $final_path/data/config.php
sudo sed -i "s@PWDTOCHANGE@$db_pwd@g" $final_path/data/config.php
sudo sed -i "s@PATHTOCHANGE@$path@g" ../conf/nginx.conf
sudo sed -i "s@ALIASTOCHANGE@$final_path/@g" ../conf/nginx.conf
sudo sed -i "s@NAMETOCHANGE@lychee@g" ../conf/nginx.conf
sudo cp ../conf/nginx.conf /etc/nginx/conf.d/$domain.d/lychee.conf

sudo sed -i "s@login@$user@g" ../conf/postini.sql
sudo sed -i "s@pwd@$user_pwd@g" ../conf/postini.sql
sudo mysql -u$db_user -p$db_pwd -D $db_user < ../conf/postini.sql

# Reload Nginx and regenerate SSOwat conf
sudo service php5-fpm restart
sudo service nginx reload
sudo yunohost app setting lychee skipped_uris -v "/"
sudo yunohost app ssowatconf
