#!/bin/bash

# Retrieve arguments
domain=$1
path=$2

# Check domain/path availability
sudo yunohost app checkurl $domain$path -a lychee
if [[ ! $? -eq 0 ]]; then
exit 1
fi
#db
db_pwd=$(dd if=/dev/urandom bs=1 count=200 2> /dev/null | tr -c -d '[A-Za-z0-9]' | sed -n 's/\(.\{24\}\).*/\1/p')
db_user=lychee

# Initialize database and store mysql password for upgrade
sudo yunohost app initdb $db_user -p $db_pwd -s $(readlink -e ../conf/db.sql) 
sudo yunohost app setting lychee mysqlpwd -v $db_pwd

# Remove trailing "/" for next commands
path=${path%/}

# Copy files to the right place
final_path=/var/www/lychee
sudo mkdir -p $final_path
sudo cp -r ../source/* $final_path
sudo cp ../conf/php-fpm.conf /etc/php5/fpm/pool.d/lychee.conf
sudo cp ../conf/php-fpm.ini /etc/php5/fpm/conf.d/20-lychee.ini
sudo cp ../conf/config.php $final_path/php/

# Set permissions to lychee directory
sudo chown -R www-data: $final_path

# Modify Nginx configuration file and copy it to Nginx conf directory
if [ -z "$path" ]; then
path="/"
fi
sudo sed -i "s@NAMETOCHANGE@lychee@g" /etc/php5/fpm/pool.d/lychee.conf
sudo sed -i "s@NAMETOCHANGE@lychee@g" $final_path/php/config.php
sudo sed -i "s@PWDTOCHANGE@$db_pwd@g" $final_path/php/config.php
sudo sed -i "s@PATHTOCHANGE@$path@g" ../conf/nginx.conf
sudo sed -i "s@ALIASTOCHANGE@$final_path/@g" ../conf/nginx.conf
sudo sed -i "s@NAMETOCHANGE@lychee@g" ../conf/nginx.conf
sudo cp ../conf/nginx.conf /etc/nginx/conf.d/$domain.d/lychee.conf


# Reload Nginx and regenerate SSOwat conf
sudo service php5-fpm restart
sudo service nginx reload
sudo yunohost app setting lychee skipped_uris -v "/"
sudo yunohost app ssowatconf
